// Exception Handling Example

let num1 = 45;
let num2 = 55;

console.log("Num1 :",num1);
console.log("Num2 :",num2);

try{
    console.log("Sum :",num1 + a);
}
catch(err){
    console.log(err);
}

console.log("Addition :",num1 + num2)


